# configs/nlp/sentiment.yaml
# @package _global_

defaults:
  - /defaults.yaml

seed_everything: 42

model:
  class_path: lmpro.modules.nlp.sentiment.SentimentClassifier
  init_args:
    vocab_size: 10000
    embed_dim: 128
    hidden_dim: 256
    num_classes: 2
    dropout_rate: 0.3
    learning_rate: 2e-4
    weight_decay: 1e-4

data:
  class_path: lmpro.datamodules.nlp_dm.NLPDataModule
  init_args:
    data_dir: data/synthetic/
    dataset_type: sentiment
    batch_size: 32
    num_workers: 4
    pin_memory: true
    max_length: 512
    vocab_size: 10000

trainer:
  max_epochs: 15
  accelerator: auto
  devices: 1
  precision: 16-mixed
  gradient_clip_val: 0.5
  accumulate_grad_batches: 1

callbacks:
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      dirpath: checkpoints/nlp/sentiment/
      filename: "sentiment-{epoch:02d}-{val_f1:.3f}"
      monitor: val_f1
      mode: max
      save_top_k: 3
      save_last: true

  - class_path: lightning.pytorch.callbacks.EarlyStopping
    init_args:
      monitor: val_f1
      mode: max
      patience: 6

  - class_path: lightning.pytorch.callbacks.LearningRateMonitor
    init_args:
      logging_interval: step

logger:
  - class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: logs/
      name: nlp_sentiment
      version: null
